name: Test language-service

on: [pull_request]

jobs:
  add-label:
    name: Add patch label to pull request
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v3
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: brpaz/hadolint-action@v1.4.0
      name: Lint container image
      with:
        dockerfile: Dockerfile

    - name: Build container
      run: docker build . -t language
    
    - name: Enforce security rules
      uses: anchore/scan-action@v2.0.4
      id: scan
      with:
        image: "language:latest"
        acs-report-enable: true

    - name: Upload scan report
      if: ${{ always() }}
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: ${{ steps.scan.outputs.sarif }}

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2.2.1
      with:
        python-version: 3.9

    - name: Install package manager
      uses: abatilo/actions-poetry@v2.1.0
      with:
        poetry-version: 1.1.4

    - name: Install dependencies
      run: poetry install

    - name: Dependency security check
      run: poetry run safety check

    - name: Check for syntax errors
      run: poetry run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Test
      run: poetry run pytest

    - name: Lint
      run: |
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        poetry run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Code security check
      run: poetry run bandit -r language_service/*

    - name: Validate code formatter
      run: poetry run black . --check
